import type { Product } from "./types";

const img = (name: string) => [`/products/${name}-1.jpg`, `/products/${name}-2.jpg`];

export const products: Product[] = [
  {
    id: "p1",
    slug: "atelier-wool-overcoat",
    name: "Atelier Wool Overcoat",
    description:
      "Italian wool overcoat with a sculpted shoulder and concealed placket. Cut for city weather and late-night drops.",
    priceUsd: 890,
    images: img("overcoat"),
    gender: "mens",
    category: "outerwear",
    collection: "Monday Program™",
    featured: true,
    variants: [
      { color: "Charcoal", size: "S", stock: 6, sku: "AW-CH-S" },
      { color: "Charcoal", size: "M", stock: 8, sku: "AW-CH-M" },
      { color: "Charcoal", size: "L", stock: 4, sku: "AW-CH-L" },
      { color: "Camel", size: "M", stock: 5, sku: "AW-CA-M" },
    ],
    lookItems: ["p4", "p17"],
  },
  {
    id: "p2",
    slug: "silk-knit-polo",
    name: "Silk Knit Polo",
    description: "Fine-gauge silk-cotton polo with tonal embroidery. Quiet luxury for everyday wear.",
    priceUsd: 245,
    images: img("polo"),
    gender: "mens",
    category: "knitwear",
    collection: "Core",
    featured: true,
    variants: [
      { color: "Ivory", size: "S", stock: 10, sku: "SK-IV-S" },
      { color: "Ivory", size: "M", stock: 12, sku: "SK-IV-M" },
      { color: "Navy", size: "M", stock: 7, sku: "SK-NV-M" },
    ],
  },
  {
    id: "p3",
    slug: "selvedge-denim-jean",
    name: "Selvedge Denim Jean",
    description: "14oz Japanese selvedge denim, tapered fit, raw hem option.",
    priceUsd: 285,
    images: img("denim"),
    gender: "mens",
    category: "denim",
    collection: "Core",
    variants: [
      { color: "Indigo", size: "30", stock: 9, sku: "SD-IN-30" },
      { color: "Indigo", size: "32", stock: 11, sku: "SD-IN-32" },
      { color: "Indigo", size: "34", stock: 6, sku: "SD-IN-34" },
    ],
  },
  {
    id: "p4",
    slug: "city-loafer",
    name: "City Loafer",
    description: "Hand-burnished leather loafer on a lightweight sole. Limited seasonal last.",
    priceUsd: 520,
    images: img("loafer"),
    gender: "mens",
    category: "footwear",
    collection: "Footwear Drop 08",
    featured: true,
    variants: [
      { color: "Black", size: "41", stock: 3, sku: "CL-BK-41" },
      { color: "Black", size: "42", stock: 5, sku: "CL-BK-42" },
      { color: "Black", size: "43", stock: 4, sku: "CL-BK-43" },
    ],
  },
  {
    id: "p5",
    slug: "raffle-runner-01",
    name: "Raffle Runner 01",
    description: "Luxury sneaker reserved for registered draws. Enter the raffle before the public drop.",
    priceUsd: 310,
    images: img("runner"),
    gender: "unisex",
    category: "footwear",
    collection: "Drawings",
    collaboration: "MAISON x Track Lab",
    featured: true,
    variants: [
      { color: "White/Orange", size: "41", stock: 1, sku: "RR-WO-41" },
      { color: "White/Orange", size: "42", stock: 2, sku: "RR-WO-42" },
      { color: "White/Orange", size: "43", stock: 1, sku: "RR-WO-43" },
    ],
  },
  {
    id: "p6",
    slug: "tailored-wool-trouser",
    name: "Tailored Wool Trouser",
    description: "High-rise wool trousers with a soft crease and side adjusters.",
    priceUsd: 340,
    images: img("trouser"),
    gender: "mens",
    category: "trousers",
    collection: "Monday Program™",
    variants: [
      { color: "Stone", size: "30", stock: 8, sku: "TW-ST-30" },
      { color: "Stone", size: "32", stock: 8, sku: "TW-ST-32" },
    ],
  },
  {
    id: "p7",
    slug: "cashmere-crew",
    name: "Cashmere Crew",
    description: "Scottish cashmere crewneck. Weightless warmth, matte finish.",
    priceUsd: 420,
    images: img("crew"),
    gender: "womens",
    category: "knitwear",
    collection: "Atelier Womens",
    featured: true,
    variants: [
      { color: "Oat", size: "XS", stock: 6, sku: "CC-OA-XS" },
      { color: "Oat", size: "S", stock: 8, sku: "CC-OA-S" },
      { color: "Black", size: "S", stock: 5, sku: "CC-BK-S" },
    ],
  },
  {
    id: "p8",
    slug: "silk-slip-dress",
    name: "Silk Slip Dress",
    description: "Bias-cut silk dress with a hidden zip and clean neckline.",
    priceUsd: 610,
    images: img("dress"),
    gender: "womens",
    category: "apparel",
    collection: "Atelier Womens",
    featured: true,
    variants: [
      { color: "Ivory", size: "XS", stock: 4, sku: "SS-IV-XS" },
      { color: "Ivory", size: "S", stock: 6, sku: "SS-IV-S" },
      { color: "Black", size: "S", stock: 5, sku: "SS-BK-S" },
    ],
    lookItems: ["p9", "p24"],
  },
  {
    id: "p9",
    slug: "leather-ankle-boot",
    name: "Leather Ankle Boot",
    description: "Stacked-heel boot in vegetable-tanned leather. Made for city rain.",
    priceUsd: 680,
    images: img("boot"),
    gender: "womens",
    category: "footwear",
    collection: "Footwear Drop 08",
    variants: [
      { color: "Espresso", size: "37", stock: 4, sku: "LB-ES-37" },
      { color: "Espresso", size: "38", stock: 5, sku: "LB-ES-38" },
      { color: "Espresso", size: "39", stock: 3, sku: "LB-ES-39" },
    ],
  },
  {
    id: "p10",
    slug: "mini-wool-parka",
    name: "Mini Wool Parka",
    description: "Kids parka in boiled wool with a hidden hood and recycled lining.",
    priceUsd: 290,
    images: img("parka"),
    gender: "kids",
    category: "outerwear",
    collection: "Maison Kids",
    variants: [
      { color: "Navy", size: "4Y", stock: 7, sku: "MP-NV-4" },
      { color: "Navy", size: "6Y", stock: 7, sku: "MP-NV-6" },
    ],
  },
  {
    id: "p11",
    slug: "wool-cap",
    name: "Wool Cap",
    description: "Structured wool cap with tonal embroidery.",
    priceUsd: 95,
    images: img("cap"),
    gender: "unisex",
    category: "accessories",
    collection: "Lifestyle",
    variants: [
      { color: "Black", size: "OS", stock: 20, sku: "WC-BK-OS" },
      { color: "Camel", size: "OS", stock: 12, sku: "WC-CA-OS" },
    ],
  },
  {
    id: "p12",
    slug: "travel-weekender",
    name: "Travel Weekender",
    description: "Vegetable-tanned leather weekender with brass hardware.",
    priceUsd: 740,
    images: img("bag"),
    gender: "unisex",
    category: "accessories",
    collection: "Lifestyle",
    featured: true,
    variants: [{ color: "Cognac", size: "OS", stock: 9, sku: "TW-CO-OS" }],
  },
  {
    id: "p13",
    slug: "signature-parfum",
    name: "Signature Parfum",
    description: "Cedar, bergamot, and smoked tea. 50ml extraits.",
    priceUsd: 185,
    images: img("parfum"),
    gender: "unisex",
    category: "lifestyle",
    collection: "Lifestyle",
    variants: [{ color: "Clear", size: "50ml", stock: 30, sku: "SP-CL-50" }],
  },
  {
    id: "p14",
    slug: "cashmere-blanket",
    name: "Cashmere Blanket",
    description: "Oversized cashmere throw. Home, hotel, or weekend house.",
    priceUsd: 460,
    images: img("blanket"),
    gender: "unisex",
    category: "lifestyle",
    collection: "Lifestyle",
    variants: [{ color: "Ivory", size: "OS", stock: 14, sku: "CB-IV-OS" }],
  },
  {
    id: "p15",
    slug: "bmw-touring-jacket",
    name: "Touring Jacket — MAISON for BMW",
    description: "Technical wool-blend touring jacket from the automotive collaboration.",
    priceUsd: 980,
    images: img("bmw"),
    gender: "mens",
    category: "outerwear",
    collection: "Collaborations",
    collaboration: "MAISON for BMW",
    featured: true,
    variants: [
      { color: "Graphite", size: "M", stock: 3, sku: "BMW-GR-M" },
      { color: "Graphite", size: "L", stock: 2, sku: "BMW-GR-L" },
    ],
  },
  {
    id: "p16",
    slug: "pitch-kit-jersey",
    name: "Pitch Kit Jersey — MAISON & Messi",
    description: "Limited football kit collaboration. Numbered edition.",
    priceUsd: 220,
    images: img("jersey"),
    gender: "unisex",
    category: "apparel",
    collection: "Collaborations",
    collaboration: "MAISON & Messi for adidas",
    featured: true,
    variants: [
      { color: "Home", size: "S", stock: 8, sku: "PK-HM-S" },
      { color: "Home", size: "M", stock: 10, sku: "PK-HM-M" },
      { color: "Home", size: "L", stock: 8, sku: "PK-HM-L" },
    ],
  },
  {
    id: "p17",
    slug: "structured-wool-blazer",
    name: "Structured Wool Blazer",
    description: "Half-canvas construction, peak lapel, and horn buttons. Boardroom to late dinner.",
    priceUsd: 780,
    images: img("blazer"),
    gender: "mens",
    category: "outerwear",
    collection: "Monday Program™",
    featured: true,
    variants: [
      { color: "Navy", size: "S", stock: 5, sku: "BL-NV-S" },
      { color: "Navy", size: "M", stock: 7, sku: "BL-NV-M" },
      { color: "Navy", size: "L", stock: 4, sku: "BL-NV-L" },
    ],
  },
  {
    id: "p18",
    slug: "heavyweight-studio-hoodie",
    name: "Heavyweight Studio Hoodie",
    description: "480gsm loopback cotton. Oversized fit with a clean kangaroo pocket.",
    priceUsd: 195,
    images: img("hoodie"),
    gender: "unisex",
    category: "apparel",
    collection: "Core",
    featured: true,
    variants: [
      { color: "Black", size: "S", stock: 14, sku: "HD-BK-S" },
      { color: "Black", size: "M", stock: 18, sku: "HD-BK-M" },
      { color: "Black", size: "L", stock: 12, sku: "HD-BK-L" },
      { color: "Grey", size: "M", stock: 10, sku: "HD-GR-M" },
    ],
  },
  {
    id: "p19",
    slug: "essential-box-tee",
    name: "Essential Box Tee",
    description: "Heavyweight jersey with a boxy silhouette and tonal neck tape.",
    priceUsd: 85,
    images: img("tee"),
    gender: "unisex",
    category: "apparel",
    collection: "Core",
    variants: [
      { color: "White", size: "S", stock: 22, sku: "ET-WH-S" },
      { color: "White", size: "M", stock: 28, sku: "ET-WH-M" },
      { color: "Black", size: "M", stock: 24, sku: "ET-BK-M" },
      { color: "Black", size: "L", stock: 16, sku: "ET-BK-L" },
    ],
  },
  {
    id: "p20",
    slug: "oxford-poplin-shirt",
    name: "Oxford Poplin Shirt",
    description: "Crisp cotton poplin with mother-of-pearl buttons and a clean cuff.",
    priceUsd: 210,
    images: img("shirt"),
    gender: "mens",
    category: "apparel",
    collection: "Core",
    variants: [
      { color: "White", size: "S", stock: 9, sku: "OX-WH-S" },
      { color: "White", size: "M", stock: 11, sku: "OX-WH-M" },
      { color: "Sky", size: "M", stock: 8, sku: "OX-SK-M" },
    ],
  },
  {
    id: "p21",
    slug: "pleated-midi-skirt",
    name: "Pleated Midi Skirt",
    description: "Fluid wool-blend pleats with a hidden side zip. Moves with the body.",
    priceUsd: 380,
    images: img("skirt"),
    gender: "womens",
    category: "apparel",
    collection: "Atelier Womens",
    featured: true,
    variants: [
      { color: "Black", size: "XS", stock: 6, sku: "SK-BK-XS" },
      { color: "Black", size: "S", stock: 8, sku: "SK-BK-S" },
      { color: "Camel", size: "S", stock: 5, sku: "SK-CA-S" },
    ],
  },
  {
    id: "p22",
    slug: "double-face-wool-coat",
    name: "Double-Face Wool Coat",
    description: "Reversible double-face wool. No lining, pure silhouette.",
    priceUsd: 1120,
    images: img("coat"),
    gender: "womens",
    category: "outerwear",
    collection: "Atelier Womens",
    featured: true,
    variants: [
      { color: "Camel", size: "XS", stock: 3, sku: "DF-CA-XS" },
      { color: "Camel", size: "S", stock: 4, sku: "DF-CA-S" },
      { color: "Camel", size: "M", stock: 3, sku: "DF-CA-M" },
    ],
  },
  {
    id: "p23",
    slug: "court-sneaker",
    name: "Court Sneaker",
    description: "Premium leather court sneaker on a gum sole. Everyday luxury.",
    priceUsd: 275,
    images: img("sneaker"),
    gender: "unisex",
    category: "footwear",
    collection: "Footwear Drop 08",
    featured: true,
    variants: [
      { color: "White", size: "40", stock: 6, sku: "CS-WH-40" },
      { color: "White", size: "41", stock: 8, sku: "CS-WH-41" },
      { color: "White", size: "42", stock: 7, sku: "CS-WH-42" },
      { color: "White", size: "43", stock: 5, sku: "CS-WH-43" },
    ],
  },
  {
    id: "p24",
    slug: "sculptural-heel",
    name: "Sculptural Heel",
    description: "Architectural heel in polished leather. Evening silhouette, day-ready height.",
    priceUsd: 590,
    images: img("heel"),
    gender: "womens",
    category: "footwear",
    collection: "Footwear Drop 08",
    variants: [
      { color: "Black", size: "37", stock: 4, sku: "SH-BK-37" },
      { color: "Black", size: "38", stock: 5, sku: "SH-BK-38" },
      { color: "Black", size: "39", stock: 3, sku: "SH-BK-39" },
    ],
  },
  {
    id: "p25",
    slug: "acetate-frame-sunglass",
    name: "Acetate Frame Sunglass",
    description: "Italian acetate frames with polarized lenses. UV400.",
    priceUsd: 260,
    images: img("sunglass"),
    gender: "unisex",
    category: "accessories",
    collection: "Lifestyle",
    featured: true,
    variants: [
      { color: "Tortoise", size: "OS", stock: 15, sku: "SG-TO-OS" },
      { color: "Black", size: "OS", stock: 18, sku: "SG-BK-OS" },
    ],
  },
  {
    id: "p26",
    slug: "automatic-field-watch",
    name: "Automatic Field Watch",
    description: "Swiss automatic movement, sapphire crystal, 40mm steel case.",
    priceUsd: 890,
    images: img("watch"),
    gender: "unisex",
    category: "accessories",
    collection: "Lifestyle",
    featured: true,
    variants: [{ color: "Steel", size: "40mm", stock: 8, sku: "AW-ST-40" }],
  },
  {
    id: "p27",
    slug: "merino-travel-scarf",
    name: "Merino Travel Scarf",
    description: "Extra-fine merino knit. Packs flat, drapes clean.",
    priceUsd: 145,
    images: img("scarf"),
    gender: "unisex",
    category: "accessories",
    collection: "Lifestyle",
    variants: [
      { color: "Charcoal", size: "OS", stock: 16, sku: "MS-CH-OS" },
      { color: "Camel", size: "OS", stock: 12, sku: "MS-CA-OS" },
    ],
  },
  {
    id: "p28",
    slug: "atelier-soy-candle",
    name: "Atelier Soy Candle",
    description: "Hand-poured soy wax. Notes of cedar, amber, and smoked vetiver. 220g.",
    priceUsd: 68,
    images: img("candle"),
    gender: "unisex",
    category: "lifestyle",
    collection: "Lifestyle",
    variants: [{ color: "Amber", size: "220g", stock: 40, sku: "AC-AM-220" }],
  },
  {
    id: "p29",
    slug: "kids-studio-tee",
    name: "Kids Studio Tee",
    description: "Soft organic cotton tee for Maison Kids. Washes well, wears soft.",
    priceUsd: 55,
    images: img("kidstee"),
    gender: "kids",
    category: "apparel",
    collection: "Maison Kids",
    variants: [
      { color: "White", size: "4Y", stock: 12, sku: "KT-WH-4" },
      { color: "White", size: "6Y", stock: 14, sku: "KT-WH-6" },
      { color: "Navy", size: "6Y", stock: 10, sku: "KT-NV-6" },
    ],
  },
  {
    id: "p30",
    slug: "signet-ring",
    name: "Signet Ring",
    description: "Solid sterling silver signet. Engraving available in-store.",
    priceUsd: 320,
    images: img("ring"),
    gender: "unisex",
    category: "accessories",
    collection: "Lifestyle",
    featured: true,
    variants: [
      { color: "Silver", size: "7", stock: 6, sku: "SR-SV-7" },
      { color: "Silver", size: "8", stock: 8, sku: "SR-SV-8" },
      { color: "Silver", size: "9", stock: 5, sku: "SR-SV-9" },
    ],
  },
];

export const bdtRate = 122;

export function convertPrice(usd: number, currency: "USD" | "BDT") {
  if (currency === "BDT") return Math.round(usd * bdtRate);
  return usd;
}

export function formatMoney(usd: number, currency: "USD" | "BDT") {
  const n = convertPrice(usd, currency);
  return currency === "BDT" ? `৳${n.toLocaleString()}` : `$${n.toLocaleString()}`;
}
